### ISSUE TITLE
not working in 2.8+

### ISSUE THREAD

**Issue by Azagwen** [FlowSoft87/MCExport#1]
I was looking for a plugin like yours, and decided to try to use it, but it seems Blender 2.8 (2019-2020) can't enable it.

Do you still work on this plugin ?

Best regards,
Aza

**Comment by FlowSoft87** [comment]
Dear Aza,

I created the plugin for Blender 2.77.
Is it possible for you to use that version?

I did not look into Blender for a longer while and can not say how much effort it would be to update to versions 2.8+.
So, for the time being the only way is to use the old version.

In the long run, I am still interested to extend the plugin and be able to use Blenders' animation tooling to create animations for Minecraft models.
But most likely not in the too near future =)

Best regards,
Flo

**Comment by Azagwen** [comment]
Hi Flo,

Thanks for your answer ! It's okay if you don't have time to work on it for now, it was already quite impressive to me to achieve such a plugin, And animation support is a thing I've searched for all over the place so it would be even more impressive to have it !

But as I said, it'd all good if you can't work on it for now.

As for your question, I could try to work with 2.77, but I have never used versions anterior to 2.79, knowing me I'd be frustrated to not have some of the latest features 2.8+ added.

For now I will stick to the good old Coding way, looking forward to when you'll feel like updating this ^^

Best regards,
Aza

**Comment by FlowSoft87** [comment]
Hi Aza,

I updated the addon and it should now work with the newest version of Blender!

Best,
Flo
