### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by Azagwen** [FlowSoft87/MCExport#2]
Some months ago I opened an issue to ask if the add-on was still being developped, and after a bit of wait it was updated, but I didn't use it right away.

And now that I want to use it, When I tried to enable the add-on I got this error message :

![image](https://user-images.githubusercontent.com/30528331/79672414-fb26e680-81d1-11ea-8092-44cb5f0309d2.png)

**Comment by RafeHall** [comment]
Seems like your installing it using the blender install button. You need to make sure you follow the install instructions in the README and ensure the folder name is MCExport.

**Comment by Azagwen** [comment]
Oh I see, now it works, my bad.
I thought it was gonna install like any other add-on ^^'
